#!/usr/bin/env bash

ASSEMBLY_NAME="${1:-}"

if [ -z "${1:-}" ]
then
  echo "ERROR: please provide an assembly name to __setup_dirnames.sh" >&2
  exit 1
fi

URL_BASE_DEFAULT="https://storage.googleapis.com/jbrowse-sscl-data"

NUCLEAR_BASENAME="${ASSEMBLY_NAME}-nuclear"
MITOCHONDRIAL_BASENAME="${ASSEMBLY_NAME}-mitochondrial"
CHLOROPLASTIC_BASENAME="${ASSEMBLY_NAME}-chloroplastic"

## Don't touch this please
NUCLEAR_ALIGNMENTS_BASENAME="${NUCLEAR_BASENAME}-alignments"
NUCLEAR_COMPOSITION_BASENAME="${NUCLEAR_BASENAME}-composition"
NUCLEAR_GENE_PREDICTIONS_BASENAME="${NUCLEAR_BASENAME}-gene_predictions"

NUCLEAR_MRNA_BASENAME="${NUCLEAR_BASENAME}-mRNA"
NUCLEAR_MRNA_FUNCTIONS_BASENAME="${NUCLEAR_MRNA_BASENAME}-functions"
NUCLEAR_MRNA_ALIGNMENTS_BASENAME="${NUCLEAR_MRNA_BASENAME}-alignments"

NUCLEAR_TE_BASENAME="${NUCLEAR_BASENAME}-TE"
NUCLEAR_RRNA_BASENAME="${NUCLEAR_BASENAME}-rRNA"
NUCLEAR_TRNA_BASENAME="${NUCLEAR_BASENAME}-tRNA"
NUCLEAR_NCRNA_BASENAME="${NUCLEAR_BASENAME}-ncRNA"
NUCLEAR_PSEUDOGENE_BASENAME="${NUCLEAR_BASENAME}-pseudogene"

NUCLEAR_PROTEIN_BASENAME="${NUCLEAR_BASENAME}-protein"
NUCLEAR_PROTEIN_FUNCTIONS_BASENAME="${NUCLEAR_PROTEIN_BASENAME}-functions"
NUCLEAR_PROTEIN_ALIGNMENTS_BASENAME="${NUCLEAR_PROTEIN_BASENAME}-alignments"

NUCLEAR_GENOMIC_ALIGNMENTS="${NUCLEAR_BASENAME}-genomic_alignments"
NUCLEAR_TRANSCRIPTOMIC_ALIGNMENTS="${NUCLEAR_BASENAME}-transcriptomic_alignments"
NUCLEAR_DATABASE_ALIGNMENTS="${NUCLEAR_BASENAME}-database_alignments"

NUCLEAR_VARIANTS_BASENAME="${NUCLEAR_BASENAME}-variants"


MITOCHONDRIAL_ALIGNMENTS_BASENAME="${MITOCHONDRIAL_BASENAME}-alignments"
MITOCHONDRIAL_COMPOSITION_BASENAME="${MITOCHONDRIAL_BASENAME}-composition"
MITOCHONDRIAL_GENE_PREDICTIONS_BASENAME="${MITOCHONDRIAL_BASENAME}-gene_predictions"

MITOCHONDRIAL_MRNA_BASENAME="${MITOCHONDRIAL_BASENAME}-mRNA"
MITOCHONDRIAL_MRNA_FUNCTIONS_BASENAME="${MITOCHONDRIAL_MRNA_BASENAME}-functions"
MITOCHONDRIAL_MRNA_ALIGNMENTS_BASENAME="${MITOCHONDRIAL_MRNA_BASENAME}-alignments"

MITOCHONDRIAL_TE_BASENAME="${MITOCHONDRIAL_BASENAME}-TE"
MITOCHONDRIAL_RRNA_BASENAME="${MITOCHONDRIAL_BASENAME}-rRNA"
MITOCHONDRIAL_TRNA_BASENAME="${MITOCHONDRIAL_BASENAME}-tRNA"
MITOCHONDRIAL_NCRNA_BASENAME="${MITOCHONDRIAL_BASENAME}-ncRNA"
MITOCHONDRIAL_PSEUDOGENE_BASENAME="${MITOCHONDRIAL_BASENAME}-pseudogene"

MITOCHONDRIAL_PROTEIN_BASENAME="${MITOCHONDRIAL_BASENAME}-protein"
MITOCHONDRIAL_PROTEIN_FUNCTIONS_BASENAME="${MITOCHONDRIAL_PROTEIN_BASENAME}-functions"
MITOCHONDRIAL_PROTEIN_ALIGNMENTS_BASENAME="${MITOCHONDRIAL_PROTEIN_BASENAME}-alignments"

MITOCHONDRIAL_GENOMIC_ALIGNMENTS="${MITOCHONDRIAL_BASENAME}-genomic_alignments"
MITOCHONDRIAL_TRANSCRIPTOMIC_ALIGNMENTS="${MITOCHONDRIAL_BASENAME}-transcriptomic_alignments"
MITOCHONDRIAL_DATABASE_ALIGNMENTS="${MITOCHONDRIAL_BASENAME}-database_alignments"

MITOCHONDRIAL_VARIANTS_BASENAME="${MITOCHONDRIAL_BASENAME}-variants"

CHLOROPLASTIC_ALIGNMENTS_BASENAME="${CHLOROPLASTIC_BASENAME}-alignments"
CHLOROPLASTIC_COMPOSITION_BASENAME="${CHLOROPLASTIC_BASENAME}-composition"
CHLOROPLASTIC_GENE_PREDICTIONS_BASENAME="${CHLOROPLASTIC_BASENAME}-gene_predictions"

CHLOROPLASTIC_MRNA_BASENAME="${CHLOROPLASTIC_BASENAME}-mRNA"
CHLOROPLASTIC_MRNA_FUNCTIONS_BASENAME="${CHLOROPLASTIC_MRNA_BASENAME}-functions"
CHLOROPLASTIC_MRNA_ALIGNMENTS_BASENAME="${CHLOROPLASTIC_MRNA_BASENAME}-alignments"

CHLOROPLASTIC_TE_BASENAME="${CHLOROPLASTIC_BASENAME}-TE"
CHLOROPLASTIC_RRNA_BASENAME="${CHLOROPLASTIC_BASENAME}-rRNA"
CHLOROPLASTIC_TRNA_BASENAME="${CHLOROPLASTIC_BASENAME}-tRNA"
CHLOROPLASTIC_NCRNA_BASENAME="${CHLOROPLASTIC_BASENAME}-ncRNA"
CHLOROPLASTIC_PSEUDOGENE_BASENAME="${CHLOROPLASTIC_BASENAME}-pseudogene"

CHLOROPLASTIC_PROTEIN_BASENAME="${CHLOROPLASTIC_BASENAME}-protein"
CHLOROPLASTIC_PROTEIN_FUNCTIONS_BASENAME="${CHLOROPLASTIC_PROTEIN_BASENAME}-functions"
CHLOROPLASTIC_PROTEIN_ALIGNMENTS_BASENAME="${CHLOROPLASTIC_PROTEIN_BASENAME}-alignments"

CHLOROPLASTIC_GENOMIC_ALIGNMENTS="${CHLOROPLASTIC_BASENAME}-genomic_alignments"
CHLOROPLASTIC_TRANSCRIPTOMIC_ALIGNMENTS="${CHLOROPLASTIC_BASENAME}-transcriptomic_alignments"
CHLOROPLASTIC_DATABASE_ALIGNMENTS="${CHLOROPLASTIC_BASENAME}-database_alignments"

CHLOROPLASTIC_VARIANTS_BASENAME="${CHLOROPLASTIC_BASENAME}-variants"
