#!/usr/bin/env bash

ASSEMBLY_NAME="${1:-}"
ASSEMBLY_KIND="${2:-nuclear}"
BASEDIR="${3}"

if [ -z "${1:-}" ]
then
  echo "ERROR: please provide an assembly name to __setup_dirnames.sh" >&2
  exit 1
fi

URL_BASE_DEFAULT="https://storage.googleapis.com/jbrowse-sscl-data"

BASENAME="${BASEDIR}/${ASSEMBLY_NAME}/${ASSEMBLY_KIND}/${ASSEMBLY_NAME}-${KIND}"

## Don't touch this please
COMPOSITION_BASENAME="${BASENAME}-composition"
FEATURE_PREDICTIONS_BASENAME="${BASENAME}-feature_predictions"

MRNA_BASENAME="${BASENAME}-mRNA"
MRNA_FUNCTIONS_BASENAME="${MRNA_BASENAME}-functions"
MRNA_ALIGNMENTS_BASENAME="${MRNA_BASENAME}-alignments"

CDS_BASENAME="${MRNA_BASENAME}-CDS"

PROTEIN_BASENAME="${MRNA_BASENAME}-protein"
PROTEIN_FUNCTIONS_BASENAME="${PROTEIN_BASENAME}-functions"
PROTEIN_ALIGNMENTS_BASENAME="${PROTEIN_BASENAME}-alignments"


TE_BASENAME="${BASENAME}-TE"
RRNA_BASENAME="${BASENAME}-rRNA"
TRNA_BASENAME="${BASENAME}-tRNA"
NCRNA_BASENAME="${BASENAME}-ncRNA"
PSEUDOGENE_BASENAME="${BASENAME}-pseudogene"

GENOMIC_ALIGNMENTS="${BASENAME}-genomic_alignments"
TRANSCRIPTOMIC_ALIGNMENTS="${BASENAME}-transcriptomic_alignments"
DATABASE_ALIGNMENTS="${BASENAME}-database_alignments"

VARIANTS_BASENAME="${BASENAME}-variants"
